### ISSUE TITLE
Poker Infoman pour avoir les creds du serveur

### ISSUE THREAD

**Issue by ldionmarcil** [aeets/informatisation#6]
Blocker pour #5

**Comment by ldionmarcil** [comment]
Impossible, selon @infoman

> Tout-d'abord, l'AÉÉTS n'est pas hébergée sur un serveur dédié, nous avons un plan de hosting illimité sur une machine partagée, donc nous n'avons pas d'accès direct au serveur lui-même

Faudrait donc considérer avoir un VPS/dedi, ou faire ça à l'interne.

**Comment by infoman** [comment]
WHAT? Is that a new form of spam?
